import type { Segment } from "./types";

export const pipeline = [
  { id: "preprocess", label: "预处理", detail: "音频标准化" },
  { id: "separation", label: "音源分离", detail: "保留背景轨" },
  { id: "segments", label: "语义分段", detail: "VAD + 说话人" },
  { id: "source_asr", label: "中文识别", detail: "Qwen3-ASR" },
  { id: "translation", label: "可控翻译", detail: "上下文 / 术语" },
  { id: "voice_clone", label: "声音克隆", detail: "CosyVoice 3" },
  { id: "target_asr", label: "英文反识别", detail: "Qwen3-ASR" },
  { id: "quality", label: "质量闸门", detail: "事实 / 音色" },
  { id: "mix", label: "混音输出", detail: "背景回混 / 响度" },
];

export const initialSegments: Segment[] = [
  {
    id: "SEG 001",
    speaker: "说话人 01",
    speakerColor: "#d7ff64",
    start: "00:00.00",
    end: "00:04.28",
    duration: 4.28,
    source: "大家好，欢迎来到今天的产品更新。",
    target: "Hello everyone, and welcome to today's product update.",
    route: "CosyVoice 3",
    status: "approved",
    semantic: 98,
    voice: 91,
    timing: 96,
  },
  {
    id: "SEG 002",
    speaker: "说话人 01",
    speakerColor: "#d7ff64",
    start: "00:04.28",
    end: "00:09.72",
    duration: 5.44,
    source: "我们计划在下个月正式开放新模型测试。",
    target: "We plan to open testing for the new model next month.",
    route: "CosyVoice 3",
    status: "approved",
    semantic: 96,
    voice: 88,
    timing: 93,
  },
  {
    id: "SEG 003",
    speaker: "说话人 02",
    speakerColor: "#78b9ff",
    start: "00:09.72",
    end: "00:14.66",
    duration: 4.94,
    source: "但这并不意味着旧版本会停止维护。",
    target: "This means the previous version will stop being maintained.",
    route: "CosyVoice 3",
    status: "review",
    semantic: 54,
    voice: 79,
    timing: 89,
    issue: "否定关系丢失",
  },
  {
    id: "SEG 004",
    speaker: "说话人 02",
    speakerColor: "#78b9ff",
    start: "00:14.66",
    end: "00:19.34",
    duration: 4.68,
    source: "现有客户仍会继续获得安全更新。",
    target: "Existing customers will continue to receive security updates.",
    route: "CosyVoice 3",
    status: "approved",
    semantic: 99,
    voice: 86,
    timing: 94,
  },
  {
    id: "SEG 005",
    speaker: "说话人 01",
    speakerColor: "#d7ff64",
    start: "00:19.34",
    end: "00:24.10",
    duration: 4.76,
    source: "更多细节会在发布会当天公布。",
    target: "More details will be announced on launch day.",
    route: "CosyVoice 3",
    status: "processing",
    semantic: 93,
    voice: 84,
    timing: 91,
  },
];
